// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RoCC.proto

package com.verif;

public final class RoCCProtos {
  private RoCCProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RoCCCommandAckOrBuilder extends
      // @@protoc_insertion_point(interface_extends:verif.RoCCCommandAck)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint32 ack = 1;</code>
     * @return The ack.
     */
    int getAck();
  }
  /**
   * Protobuf type {@code verif.RoCCCommandAck}
   */
  public static final class RoCCCommandAck extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:verif.RoCCCommandAck)
      RoCCCommandAckOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use RoCCCommandAck.newBuilder() to construct.
    private RoCCCommandAck(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RoCCCommandAck() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new RoCCCommandAck();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private RoCCCommandAck(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              ack_ = input.readUInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.verif.RoCCProtos.internal_static_verif_RoCCCommandAck_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.verif.RoCCProtos.internal_static_verif_RoCCCommandAck_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.verif.RoCCProtos.RoCCCommandAck.class, com.verif.RoCCProtos.RoCCCommandAck.Builder.class);
    }

    public static final int ACK_FIELD_NUMBER = 1;
    private int ack_;
    /**
     * <code>uint32 ack = 1;</code>
     * @return The ack.
     */
    @java.lang.Override
    public int getAck() {
      return ack_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (ack_ != 0) {
        output.writeUInt32(1, ack_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (ack_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, ack_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.verif.RoCCProtos.RoCCCommandAck)) {
        return super.equals(obj);
      }
      com.verif.RoCCProtos.RoCCCommandAck other = (com.verif.RoCCProtos.RoCCCommandAck) obj;

      if (getAck()
          != other.getAck()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ACK_FIELD_NUMBER;
      hash = (53 * hash) + getAck();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.verif.RoCCProtos.RoCCCommandAck parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.verif.RoCCProtos.RoCCCommandAck parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.verif.RoCCProtos.RoCCCommandAck parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.verif.RoCCProtos.RoCCCommandAck parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.verif.RoCCProtos.RoCCCommandAck parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.verif.RoCCProtos.RoCCCommandAck parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.verif.RoCCProtos.RoCCCommandAck parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.verif.RoCCProtos.RoCCCommandAck parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.verif.RoCCProtos.RoCCCommandAck parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.verif.RoCCProtos.RoCCCommandAck parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.verif.RoCCProtos.RoCCCommandAck parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.verif.RoCCProtos.RoCCCommandAck parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.verif.RoCCProtos.RoCCCommandAck prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code verif.RoCCCommandAck}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:verif.RoCCCommandAck)
        com.verif.RoCCProtos.RoCCCommandAckOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.verif.RoCCProtos.internal_static_verif_RoCCCommandAck_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.verif.RoCCProtos.internal_static_verif_RoCCCommandAck_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.verif.RoCCProtos.RoCCCommandAck.class, com.verif.RoCCProtos.RoCCCommandAck.Builder.class);
      }

      // Construct using com.verif.RoCCProtos.RoCCCommandAck.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        ack_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.verif.RoCCProtos.internal_static_verif_RoCCCommandAck_descriptor;
      }

      @java.lang.Override
      public com.verif.RoCCProtos.RoCCCommandAck getDefaultInstanceForType() {
        return com.verif.RoCCProtos.RoCCCommandAck.getDefaultInstance();
      }

      @java.lang.Override
      public com.verif.RoCCProtos.RoCCCommandAck build() {
        com.verif.RoCCProtos.RoCCCommandAck result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.verif.RoCCProtos.RoCCCommandAck buildPartial() {
        com.verif.RoCCProtos.RoCCCommandAck result = new com.verif.RoCCProtos.RoCCCommandAck(this);
        result.ack_ = ack_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.verif.RoCCProtos.RoCCCommandAck) {
          return mergeFrom((com.verif.RoCCProtos.RoCCCommandAck)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.verif.RoCCProtos.RoCCCommandAck other) {
        if (other == com.verif.RoCCProtos.RoCCCommandAck.getDefaultInstance()) return this;
        if (other.getAck() != 0) {
          setAck(other.getAck());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.verif.RoCCProtos.RoCCCommandAck parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.verif.RoCCProtos.RoCCCommandAck) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int ack_ ;
      /**
       * <code>uint32 ack = 1;</code>
       * @return The ack.
       */
      @java.lang.Override
      public int getAck() {
        return ack_;
      }
      /**
       * <code>uint32 ack = 1;</code>
       * @param value The ack to set.
       * @return This builder for chaining.
       */
      public Builder setAck(int value) {
        
        ack_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 ack = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearAck() {
        
        ack_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:verif.RoCCCommandAck)
    }

    // @@protoc_insertion_point(class_scope:verif.RoCCCommandAck)
    private static final com.verif.RoCCProtos.RoCCCommandAck DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.verif.RoCCProtos.RoCCCommandAck();
    }

    public static com.verif.RoCCProtos.RoCCCommandAck getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RoCCCommandAck>
        PARSER = new com.google.protobuf.AbstractParser<RoCCCommandAck>() {
      @java.lang.Override
      public RoCCCommandAck parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RoCCCommandAck(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RoCCCommandAck> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RoCCCommandAck> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.verif.RoCCProtos.RoCCCommandAck getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface RoCCInstructionOrBuilder extends
      // @@protoc_insertion_point(interface_extends:verif.RoCCInstruction)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint32 funct = 1;</code>
     * @return The funct.
     */
    int getFunct();

    /**
     * <code>uint32 rs2 = 2;</code>
     * @return The rs2.
     */
    int getRs2();

    /**
     * <code>uint32 rs1 = 3;</code>
     * @return The rs1.
     */
    int getRs1();

    /**
     * <code>bool xd = 4;</code>
     * @return The xd.
     */
    boolean getXd();

    /**
     * <code>bool xs1 = 5;</code>
     * @return The xs1.
     */
    boolean getXs1();

    /**
     * <code>bool xs2 = 6;</code>
     * @return The xs2.
     */
    boolean getXs2();

    /**
     * <code>uint32 rd = 7;</code>
     * @return The rd.
     */
    int getRd();

    /**
     * <code>uint32 opcode = 8;</code>
     * @return The opcode.
     */
    int getOpcode();
  }
  /**
   * Protobuf type {@code verif.RoCCInstruction}
   */
  public static final class RoCCInstruction extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:verif.RoCCInstruction)
      RoCCInstructionOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use RoCCInstruction.newBuilder() to construct.
    private RoCCInstruction(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RoCCInstruction() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new RoCCInstruction();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private RoCCInstruction(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              funct_ = input.readUInt32();
              break;
            }
            case 16: {

              rs2_ = input.readUInt32();
              break;
            }
            case 24: {

              rs1_ = input.readUInt32();
              break;
            }
            case 32: {

              xd_ = input.readBool();
              break;
            }
            case 40: {

              xs1_ = input.readBool();
              break;
            }
            case 48: {

              xs2_ = input.readBool();
              break;
            }
            case 56: {

              rd_ = input.readUInt32();
              break;
            }
            case 64: {

              opcode_ = input.readUInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.verif.RoCCProtos.internal_static_verif_RoCCInstruction_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.verif.RoCCProtos.internal_static_verif_RoCCInstruction_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.verif.RoCCProtos.RoCCInstruction.class, com.verif.RoCCProtos.RoCCInstruction.Builder.class);
    }

    public static final int FUNCT_FIELD_NUMBER = 1;
    private int funct_;
    /**
     * <code>uint32 funct = 1;</code>
     * @return The funct.
     */
    @java.lang.Override
    public int getFunct() {
      return funct_;
    }

    public static final int RS2_FIELD_NUMBER = 2;
    private int rs2_;
    /**
     * <code>uint32 rs2 = 2;</code>
     * @return The rs2.
     */
    @java.lang.Override
    public int getRs2() {
      return rs2_;
    }

    public static final int RS1_FIELD_NUMBER = 3;
    private int rs1_;
    /**
     * <code>uint32 rs1 = 3;</code>
     * @return The rs1.
     */
    @java.lang.Override
    public int getRs1() {
      return rs1_;
    }

    public static final int XD_FIELD_NUMBER = 4;
    private boolean xd_;
    /**
     * <code>bool xd = 4;</code>
     * @return The xd.
     */
    @java.lang.Override
    public boolean getXd() {
      return xd_;
    }

    public static final int XS1_FIELD_NUMBER = 5;
    private boolean xs1_;
    /**
     * <code>bool xs1 = 5;</code>
     * @return The xs1.
     */
    @java.lang.Override
    public boolean getXs1() {
      return xs1_;
    }

    public static final int XS2_FIELD_NUMBER = 6;
    private boolean xs2_;
    /**
     * <code>bool xs2 = 6;</code>
     * @return The xs2.
     */
    @java.lang.Override
    public boolean getXs2() {
      return xs2_;
    }

    public static final int RD_FIELD_NUMBER = 7;
    private int rd_;
    /**
     * <code>uint32 rd = 7;</code>
     * @return The rd.
     */
    @java.lang.Override
    public int getRd() {
      return rd_;
    }

    public static final int OPCODE_FIELD_NUMBER = 8;
    private int opcode_;
    /**
     * <code>uint32 opcode = 8;</code>
     * @return The opcode.
     */
    @java.lang.Override
    public int getOpcode() {
      return opcode_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (funct_ != 0) {
        output.writeUInt32(1, funct_);
      }
      if (rs2_ != 0) {
        output.writeUInt32(2, rs2_);
      }
      if (rs1_ != 0) {
        output.writeUInt32(3, rs1_);
      }
      if (xd_ != false) {
        output.writeBool(4, xd_);
      }
      if (xs1_ != false) {
        output.writeBool(5, xs1_);
      }
      if (xs2_ != false) {
        output.writeBool(6, xs2_);
      }
      if (rd_ != 0) {
        output.writeUInt32(7, rd_);
      }
      if (opcode_ != 0) {
        output.writeUInt32(8, opcode_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (funct_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, funct_);
      }
      if (rs2_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, rs2_);
      }
      if (rs1_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, rs1_);
      }
      if (xd_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(4, xd_);
      }
      if (xs1_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(5, xs1_);
      }
      if (xs2_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(6, xs2_);
      }
      if (rd_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(7, rd_);
      }
      if (opcode_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(8, opcode_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.verif.RoCCProtos.RoCCInstruction)) {
        return super.equals(obj);
      }
      com.verif.RoCCProtos.RoCCInstruction other = (com.verif.RoCCProtos.RoCCInstruction) obj;

      if (getFunct()
          != other.getFunct()) return false;
      if (getRs2()
          != other.getRs2()) return false;
      if (getRs1()
          != other.getRs1()) return false;
      if (getXd()
          != other.getXd()) return false;
      if (getXs1()
          != other.getXs1()) return false;
      if (getXs2()
          != other.getXs2()) return false;
      if (getRd()
          != other.getRd()) return false;
      if (getOpcode()
          != other.getOpcode()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + FUNCT_FIELD_NUMBER;
      hash = (53 * hash) + getFunct();
      hash = (37 * hash) + RS2_FIELD_NUMBER;
      hash = (53 * hash) + getRs2();
      hash = (37 * hash) + RS1_FIELD_NUMBER;
      hash = (53 * hash) + getRs1();
      hash = (37 * hash) + XD_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getXd());
      hash = (37 * hash) + XS1_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getXs1());
      hash = (37 * hash) + XS2_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getXs2());
      hash = (37 * hash) + RD_FIELD_NUMBER;
      hash = (53 * hash) + getRd();
      hash = (37 * hash) + OPCODE_FIELD_NUMBER;
      hash = (53 * hash) + getOpcode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.verif.RoCCProtos.RoCCInstruction parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.verif.RoCCProtos.RoCCInstruction parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.verif.RoCCProtos.RoCCInstruction parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.verif.RoCCProtos.RoCCInstruction parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.verif.RoCCProtos.RoCCInstruction parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.verif.RoCCProtos.RoCCInstruction parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.verif.RoCCProtos.RoCCInstruction parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.verif.RoCCProtos.RoCCInstruction parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.verif.RoCCProtos.RoCCInstruction parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.verif.RoCCProtos.RoCCInstruction parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.verif.RoCCProtos.RoCCInstruction parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.verif.RoCCProtos.RoCCInstruction parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.verif.RoCCProtos.RoCCInstruction prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code verif.RoCCInstruction}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:verif.RoCCInstruction)
        com.verif.RoCCProtos.RoCCInstructionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.verif.RoCCProtos.internal_static_verif_RoCCInstruction_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.verif.RoCCProtos.internal_static_verif_RoCCInstruction_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.verif.RoCCProtos.RoCCInstruction.class, com.verif.RoCCProtos.RoCCInstruction.Builder.class);
      }

      // Construct using com.verif.RoCCProtos.RoCCInstruction.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        funct_ = 0;

        rs2_ = 0;

        rs1_ = 0;

        xd_ = false;

        xs1_ = false;

        xs2_ = false;

        rd_ = 0;

        opcode_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.verif.RoCCProtos.internal_static_verif_RoCCInstruction_descriptor;
      }

      @java.lang.Override
      public com.verif.RoCCProtos.RoCCInstruction getDefaultInstanceForType() {
        return com.verif.RoCCProtos.RoCCInstruction.getDefaultInstance();
      }

      @java.lang.Override
      public com.verif.RoCCProtos.RoCCInstruction build() {
        com.verif.RoCCProtos.RoCCInstruction result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.verif.RoCCProtos.RoCCInstruction buildPartial() {
        com.verif.RoCCProtos.RoCCInstruction result = new com.verif.RoCCProtos.RoCCInstruction(this);
        result.funct_ = funct_;
        result.rs2_ = rs2_;
        result.rs1_ = rs1_;
        result.xd_ = xd_;
        result.xs1_ = xs1_;
        result.xs2_ = xs2_;
        result.rd_ = rd_;
        result.opcode_ = opcode_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.verif.RoCCProtos.RoCCInstruction) {
          return mergeFrom((com.verif.RoCCProtos.RoCCInstruction)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.verif.RoCCProtos.RoCCInstruction other) {
        if (other == com.verif.RoCCProtos.RoCCInstruction.getDefaultInstance()) return this;
        if (other.getFunct() != 0) {
          setFunct(other.getFunct());
        }
        if (other.getRs2() != 0) {
          setRs2(other.getRs2());
        }
        if (other.getRs1() != 0) {
          setRs1(other.getRs1());
        }
        if (other.getXd() != false) {
          setXd(other.getXd());
        }
        if (other.getXs1() != false) {
          setXs1(other.getXs1());
        }
        if (other.getXs2() != false) {
          setXs2(other.getXs2());
        }
        if (other.getRd() != 0) {
          setRd(other.getRd());
        }
        if (other.getOpcode() != 0) {
          setOpcode(other.getOpcode());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.verif.RoCCProtos.RoCCInstruction parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.verif.RoCCProtos.RoCCInstruction) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int funct_ ;
      /**
       * <code>uint32 funct = 1;</code>
       * @return The funct.
       */
      @java.lang.Override
      public int getFunct() {
        return funct_;
      }
      /**
       * <code>uint32 funct = 1;</code>
       * @param value The funct to set.
       * @return This builder for chaining.
       */
      public Builder setFunct(int value) {
        
        funct_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 funct = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearFunct() {
        
        funct_ = 0;
        onChanged();
        return this;
      }

      private int rs2_ ;
      /**
       * <code>uint32 rs2 = 2;</code>
       * @return The rs2.
       */
      @java.lang.Override
      public int getRs2() {
        return rs2_;
      }
      /**
       * <code>uint32 rs2 = 2;</code>
       * @param value The rs2 to set.
       * @return This builder for chaining.
       */
      public Builder setRs2(int value) {
        
        rs2_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 rs2 = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearRs2() {
        
        rs2_ = 0;
        onChanged();
        return this;
      }

      private int rs1_ ;
      /**
       * <code>uint32 rs1 = 3;</code>
       * @return The rs1.
       */
      @java.lang.Override
      public int getRs1() {
        return rs1_;
      }
      /**
       * <code>uint32 rs1 = 3;</code>
       * @param value The rs1 to set.
       * @return This builder for chaining.
       */
      public Builder setRs1(int value) {
        
        rs1_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 rs1 = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearRs1() {
        
        rs1_ = 0;
        onChanged();
        return this;
      }

      private boolean xd_ ;
      /**
       * <code>bool xd = 4;</code>
       * @return The xd.
       */
      @java.lang.Override
      public boolean getXd() {
        return xd_;
      }
      /**
       * <code>bool xd = 4;</code>
       * @param value The xd to set.
       * @return This builder for chaining.
       */
      public Builder setXd(boolean value) {
        
        xd_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool xd = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearXd() {
        
        xd_ = false;
        onChanged();
        return this;
      }

      private boolean xs1_ ;
      /**
       * <code>bool xs1 = 5;</code>
       * @return The xs1.
       */
      @java.lang.Override
      public boolean getXs1() {
        return xs1_;
      }
      /**
       * <code>bool xs1 = 5;</code>
       * @param value The xs1 to set.
       * @return This builder for chaining.
       */
      public Builder setXs1(boolean value) {
        
        xs1_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool xs1 = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearXs1() {
        
        xs1_ = false;
        onChanged();
        return this;
      }

      private boolean xs2_ ;
      /**
       * <code>bool xs2 = 6;</code>
       * @return The xs2.
       */
      @java.lang.Override
      public boolean getXs2() {
        return xs2_;
      }
      /**
       * <code>bool xs2 = 6;</code>
       * @param value The xs2 to set.
       * @return This builder for chaining.
       */
      public Builder setXs2(boolean value) {
        
        xs2_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool xs2 = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearXs2() {
        
        xs2_ = false;
        onChanged();
        return this;
      }

      private int rd_ ;
      /**
       * <code>uint32 rd = 7;</code>
       * @return The rd.
       */
      @java.lang.Override
      public int getRd() {
        return rd_;
      }
      /**
       * <code>uint32 rd = 7;</code>
       * @param value The rd to set.
       * @return This builder for chaining.
       */
      public Builder setRd(int value) {
        
        rd_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 rd = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearRd() {
        
        rd_ = 0;
        onChanged();
        return this;
      }

      private int opcode_ ;
      /**
       * <code>uint32 opcode = 8;</code>
       * @return The opcode.
       */
      @java.lang.Override
      public int getOpcode() {
        return opcode_;
      }
      /**
       * <code>uint32 opcode = 8;</code>
       * @param value The opcode to set.
       * @return This builder for chaining.
       */
      public Builder setOpcode(int value) {
        
        opcode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 opcode = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearOpcode() {
        
        opcode_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:verif.RoCCInstruction)
    }

    // @@protoc_insertion_point(class_scope:verif.RoCCInstruction)
    private static final com.verif.RoCCProtos.RoCCInstruction DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.verif.RoCCProtos.RoCCInstruction();
    }

    public static com.verif.RoCCProtos.RoCCInstruction getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RoCCInstruction>
        PARSER = new com.google.protobuf.AbstractParser<RoCCInstruction>() {
      @java.lang.Override
      public RoCCInstruction parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RoCCInstruction(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RoCCInstruction> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RoCCInstruction> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.verif.RoCCProtos.RoCCInstruction getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface RoCCCommandOrBuilder extends
      // @@protoc_insertion_point(interface_extends:verif.RoCCCommand)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.verif.RoCCInstruction inst = 1;</code>
     * @return Whether the inst field is set.
     */
    boolean hasInst();
    /**
     * <code>.verif.RoCCInstruction inst = 1;</code>
     * @return The inst.
     */
    com.verif.RoCCProtos.RoCCInstruction getInst();
    /**
     * <code>.verif.RoCCInstruction inst = 1;</code>
     */
    com.verif.RoCCProtos.RoCCInstructionOrBuilder getInstOrBuilder();

    /**
     * <code>uint64 rs1 = 2;</code>
     * @return The rs1.
     */
    long getRs1();

    /**
     * <code>uint64 rs2 = 3;</code>
     * @return The rs2.
     */
    long getRs2();
  }
  /**
   * Protobuf type {@code verif.RoCCCommand}
   */
  public static final class RoCCCommand extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:verif.RoCCCommand)
      RoCCCommandOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use RoCCCommand.newBuilder() to construct.
    private RoCCCommand(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RoCCCommand() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new RoCCCommand();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private RoCCCommand(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.verif.RoCCProtos.RoCCInstruction.Builder subBuilder = null;
              if (inst_ != null) {
                subBuilder = inst_.toBuilder();
              }
              inst_ = input.readMessage(com.verif.RoCCProtos.RoCCInstruction.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(inst_);
                inst_ = subBuilder.buildPartial();
              }

              break;
            }
            case 16: {

              rs1_ = input.readUInt64();
              break;
            }
            case 24: {

              rs2_ = input.readUInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.verif.RoCCProtos.internal_static_verif_RoCCCommand_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.verif.RoCCProtos.internal_static_verif_RoCCCommand_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.verif.RoCCProtos.RoCCCommand.class, com.verif.RoCCProtos.RoCCCommand.Builder.class);
    }

    public static final int INST_FIELD_NUMBER = 1;
    private com.verif.RoCCProtos.RoCCInstruction inst_;
    /**
     * <code>.verif.RoCCInstruction inst = 1;</code>
     * @return Whether the inst field is set.
     */
    @java.lang.Override
    public boolean hasInst() {
      return inst_ != null;
    }
    /**
     * <code>.verif.RoCCInstruction inst = 1;</code>
     * @return The inst.
     */
    @java.lang.Override
    public com.verif.RoCCProtos.RoCCInstruction getInst() {
      return inst_ == null ? com.verif.RoCCProtos.RoCCInstruction.getDefaultInstance() : inst_;
    }
    /**
     * <code>.verif.RoCCInstruction inst = 1;</code>
     */
    @java.lang.Override
    public com.verif.RoCCProtos.RoCCInstructionOrBuilder getInstOrBuilder() {
      return getInst();
    }

    public static final int RS1_FIELD_NUMBER = 2;
    private long rs1_;
    /**
     * <code>uint64 rs1 = 2;</code>
     * @return The rs1.
     */
    @java.lang.Override
    public long getRs1() {
      return rs1_;
    }

    public static final int RS2_FIELD_NUMBER = 3;
    private long rs2_;
    /**
     * <code>uint64 rs2 = 3;</code>
     * @return The rs2.
     */
    @java.lang.Override
    public long getRs2() {
      return rs2_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (inst_ != null) {
        output.writeMessage(1, getInst());
      }
      if (rs1_ != 0L) {
        output.writeUInt64(2, rs1_);
      }
      if (rs2_ != 0L) {
        output.writeUInt64(3, rs2_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (inst_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getInst());
      }
      if (rs1_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, rs1_);
      }
      if (rs2_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(3, rs2_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.verif.RoCCProtos.RoCCCommand)) {
        return super.equals(obj);
      }
      com.verif.RoCCProtos.RoCCCommand other = (com.verif.RoCCProtos.RoCCCommand) obj;

      if (hasInst() != other.hasInst()) return false;
      if (hasInst()) {
        if (!getInst()
            .equals(other.getInst())) return false;
      }
      if (getRs1()
          != other.getRs1()) return false;
      if (getRs2()
          != other.getRs2()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasInst()) {
        hash = (37 * hash) + INST_FIELD_NUMBER;
        hash = (53 * hash) + getInst().hashCode();
      }
      hash = (37 * hash) + RS1_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getRs1());
      hash = (37 * hash) + RS2_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getRs2());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.verif.RoCCProtos.RoCCCommand parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.verif.RoCCProtos.RoCCCommand parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.verif.RoCCProtos.RoCCCommand parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.verif.RoCCProtos.RoCCCommand parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.verif.RoCCProtos.RoCCCommand parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.verif.RoCCProtos.RoCCCommand parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.verif.RoCCProtos.RoCCCommand parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.verif.RoCCProtos.RoCCCommand parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.verif.RoCCProtos.RoCCCommand parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.verif.RoCCProtos.RoCCCommand parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.verif.RoCCProtos.RoCCCommand parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.verif.RoCCProtos.RoCCCommand parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.verif.RoCCProtos.RoCCCommand prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code verif.RoCCCommand}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:verif.RoCCCommand)
        com.verif.RoCCProtos.RoCCCommandOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.verif.RoCCProtos.internal_static_verif_RoCCCommand_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.verif.RoCCProtos.internal_static_verif_RoCCCommand_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.verif.RoCCProtos.RoCCCommand.class, com.verif.RoCCProtos.RoCCCommand.Builder.class);
      }

      // Construct using com.verif.RoCCProtos.RoCCCommand.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (instBuilder_ == null) {
          inst_ = null;
        } else {
          inst_ = null;
          instBuilder_ = null;
        }
        rs1_ = 0L;

        rs2_ = 0L;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.verif.RoCCProtos.internal_static_verif_RoCCCommand_descriptor;
      }

      @java.lang.Override
      public com.verif.RoCCProtos.RoCCCommand getDefaultInstanceForType() {
        return com.verif.RoCCProtos.RoCCCommand.getDefaultInstance();
      }

      @java.lang.Override
      public com.verif.RoCCProtos.RoCCCommand build() {
        com.verif.RoCCProtos.RoCCCommand result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.verif.RoCCProtos.RoCCCommand buildPartial() {
        com.verif.RoCCProtos.RoCCCommand result = new com.verif.RoCCProtos.RoCCCommand(this);
        if (instBuilder_ == null) {
          result.inst_ = inst_;
        } else {
          result.inst_ = instBuilder_.build();
        }
        result.rs1_ = rs1_;
        result.rs2_ = rs2_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.verif.RoCCProtos.RoCCCommand) {
          return mergeFrom((com.verif.RoCCProtos.RoCCCommand)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.verif.RoCCProtos.RoCCCommand other) {
        if (other == com.verif.RoCCProtos.RoCCCommand.getDefaultInstance()) return this;
        if (other.hasInst()) {
          mergeInst(other.getInst());
        }
        if (other.getRs1() != 0L) {
          setRs1(other.getRs1());
        }
        if (other.getRs2() != 0L) {
          setRs2(other.getRs2());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.verif.RoCCProtos.RoCCCommand parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.verif.RoCCProtos.RoCCCommand) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.verif.RoCCProtos.RoCCInstruction inst_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.verif.RoCCProtos.RoCCInstruction, com.verif.RoCCProtos.RoCCInstruction.Builder, com.verif.RoCCProtos.RoCCInstructionOrBuilder> instBuilder_;
      /**
       * <code>.verif.RoCCInstruction inst = 1;</code>
       * @return Whether the inst field is set.
       */
      public boolean hasInst() {
        return instBuilder_ != null || inst_ != null;
      }
      /**
       * <code>.verif.RoCCInstruction inst = 1;</code>
       * @return The inst.
       */
      public com.verif.RoCCProtos.RoCCInstruction getInst() {
        if (instBuilder_ == null) {
          return inst_ == null ? com.verif.RoCCProtos.RoCCInstruction.getDefaultInstance() : inst_;
        } else {
          return instBuilder_.getMessage();
        }
      }
      /**
       * <code>.verif.RoCCInstruction inst = 1;</code>
       */
      public Builder setInst(com.verif.RoCCProtos.RoCCInstruction value) {
        if (instBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          inst_ = value;
          onChanged();
        } else {
          instBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.verif.RoCCInstruction inst = 1;</code>
       */
      public Builder setInst(
          com.verif.RoCCProtos.RoCCInstruction.Builder builderForValue) {
        if (instBuilder_ == null) {
          inst_ = builderForValue.build();
          onChanged();
        } else {
          instBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.verif.RoCCInstruction inst = 1;</code>
       */
      public Builder mergeInst(com.verif.RoCCProtos.RoCCInstruction value) {
        if (instBuilder_ == null) {
          if (inst_ != null) {
            inst_ =
              com.verif.RoCCProtos.RoCCInstruction.newBuilder(inst_).mergeFrom(value).buildPartial();
          } else {
            inst_ = value;
          }
          onChanged();
        } else {
          instBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.verif.RoCCInstruction inst = 1;</code>
       */
      public Builder clearInst() {
        if (instBuilder_ == null) {
          inst_ = null;
          onChanged();
        } else {
          inst_ = null;
          instBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.verif.RoCCInstruction inst = 1;</code>
       */
      public com.verif.RoCCProtos.RoCCInstruction.Builder getInstBuilder() {
        
        onChanged();
        return getInstFieldBuilder().getBuilder();
      }
      /**
       * <code>.verif.RoCCInstruction inst = 1;</code>
       */
      public com.verif.RoCCProtos.RoCCInstructionOrBuilder getInstOrBuilder() {
        if (instBuilder_ != null) {
          return instBuilder_.getMessageOrBuilder();
        } else {
          return inst_ == null ?
              com.verif.RoCCProtos.RoCCInstruction.getDefaultInstance() : inst_;
        }
      }
      /**
       * <code>.verif.RoCCInstruction inst = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.verif.RoCCProtos.RoCCInstruction, com.verif.RoCCProtos.RoCCInstruction.Builder, com.verif.RoCCProtos.RoCCInstructionOrBuilder> 
          getInstFieldBuilder() {
        if (instBuilder_ == null) {
          instBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.verif.RoCCProtos.RoCCInstruction, com.verif.RoCCProtos.RoCCInstruction.Builder, com.verif.RoCCProtos.RoCCInstructionOrBuilder>(
                  getInst(),
                  getParentForChildren(),
                  isClean());
          inst_ = null;
        }
        return instBuilder_;
      }

      private long rs1_ ;
      /**
       * <code>uint64 rs1 = 2;</code>
       * @return The rs1.
       */
      @java.lang.Override
      public long getRs1() {
        return rs1_;
      }
      /**
       * <code>uint64 rs1 = 2;</code>
       * @param value The rs1 to set.
       * @return This builder for chaining.
       */
      public Builder setRs1(long value) {
        
        rs1_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 rs1 = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearRs1() {
        
        rs1_ = 0L;
        onChanged();
        return this;
      }

      private long rs2_ ;
      /**
       * <code>uint64 rs2 = 3;</code>
       * @return The rs2.
       */
      @java.lang.Override
      public long getRs2() {
        return rs2_;
      }
      /**
       * <code>uint64 rs2 = 3;</code>
       * @param value The rs2 to set.
       * @return This builder for chaining.
       */
      public Builder setRs2(long value) {
        
        rs2_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 rs2 = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearRs2() {
        
        rs2_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:verif.RoCCCommand)
    }

    // @@protoc_insertion_point(class_scope:verif.RoCCCommand)
    private static final com.verif.RoCCProtos.RoCCCommand DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.verif.RoCCProtos.RoCCCommand();
    }

    public static com.verif.RoCCProtos.RoCCCommand getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RoCCCommand>
        PARSER = new com.google.protobuf.AbstractParser<RoCCCommand>() {
      @java.lang.Override
      public RoCCCommand parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RoCCCommand(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RoCCCommand> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RoCCCommand> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.verif.RoCCProtos.RoCCCommand getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface RoCCResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:verif.RoCCResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint32 rd = 1;</code>
     * @return The rd.
     */
    int getRd();

    /**
     * <code>uint64 data = 2;</code>
     * @return The data.
     */
    long getData();
  }
  /**
   * Protobuf type {@code verif.RoCCResponse}
   */
  public static final class RoCCResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:verif.RoCCResponse)
      RoCCResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use RoCCResponse.newBuilder() to construct.
    private RoCCResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RoCCResponse() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new RoCCResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private RoCCResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              rd_ = input.readUInt32();
              break;
            }
            case 16: {

              data_ = input.readUInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.verif.RoCCProtos.internal_static_verif_RoCCResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.verif.RoCCProtos.internal_static_verif_RoCCResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.verif.RoCCProtos.RoCCResponse.class, com.verif.RoCCProtos.RoCCResponse.Builder.class);
    }

    public static final int RD_FIELD_NUMBER = 1;
    private int rd_;
    /**
     * <code>uint32 rd = 1;</code>
     * @return The rd.
     */
    @java.lang.Override
    public int getRd() {
      return rd_;
    }

    public static final int DATA_FIELD_NUMBER = 2;
    private long data_;
    /**
     * <code>uint64 data = 2;</code>
     * @return The data.
     */
    @java.lang.Override
    public long getData() {
      return data_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (rd_ != 0) {
        output.writeUInt32(1, rd_);
      }
      if (data_ != 0L) {
        output.writeUInt64(2, data_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (rd_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, rd_);
      }
      if (data_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, data_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.verif.RoCCProtos.RoCCResponse)) {
        return super.equals(obj);
      }
      com.verif.RoCCProtos.RoCCResponse other = (com.verif.RoCCProtos.RoCCResponse) obj;

      if (getRd()
          != other.getRd()) return false;
      if (getData()
          != other.getData()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + RD_FIELD_NUMBER;
      hash = (53 * hash) + getRd();
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getData());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.verif.RoCCProtos.RoCCResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.verif.RoCCProtos.RoCCResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.verif.RoCCProtos.RoCCResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.verif.RoCCProtos.RoCCResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.verif.RoCCProtos.RoCCResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.verif.RoCCProtos.RoCCResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.verif.RoCCProtos.RoCCResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.verif.RoCCProtos.RoCCResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.verif.RoCCProtos.RoCCResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.verif.RoCCProtos.RoCCResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.verif.RoCCProtos.RoCCResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.verif.RoCCProtos.RoCCResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.verif.RoCCProtos.RoCCResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code verif.RoCCResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:verif.RoCCResponse)
        com.verif.RoCCProtos.RoCCResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.verif.RoCCProtos.internal_static_verif_RoCCResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.verif.RoCCProtos.internal_static_verif_RoCCResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.verif.RoCCProtos.RoCCResponse.class, com.verif.RoCCProtos.RoCCResponse.Builder.class);
      }

      // Construct using com.verif.RoCCProtos.RoCCResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        rd_ = 0;

        data_ = 0L;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.verif.RoCCProtos.internal_static_verif_RoCCResponse_descriptor;
      }

      @java.lang.Override
      public com.verif.RoCCProtos.RoCCResponse getDefaultInstanceForType() {
        return com.verif.RoCCProtos.RoCCResponse.getDefaultInstance();
      }

      @java.lang.Override
      public com.verif.RoCCProtos.RoCCResponse build() {
        com.verif.RoCCProtos.RoCCResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.verif.RoCCProtos.RoCCResponse buildPartial() {
        com.verif.RoCCProtos.RoCCResponse result = new com.verif.RoCCProtos.RoCCResponse(this);
        result.rd_ = rd_;
        result.data_ = data_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.verif.RoCCProtos.RoCCResponse) {
          return mergeFrom((com.verif.RoCCProtos.RoCCResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.verif.RoCCProtos.RoCCResponse other) {
        if (other == com.verif.RoCCProtos.RoCCResponse.getDefaultInstance()) return this;
        if (other.getRd() != 0) {
          setRd(other.getRd());
        }
        if (other.getData() != 0L) {
          setData(other.getData());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.verif.RoCCProtos.RoCCResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.verif.RoCCProtos.RoCCResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int rd_ ;
      /**
       * <code>uint32 rd = 1;</code>
       * @return The rd.
       */
      @java.lang.Override
      public int getRd() {
        return rd_;
      }
      /**
       * <code>uint32 rd = 1;</code>
       * @param value The rd to set.
       * @return This builder for chaining.
       */
      public Builder setRd(int value) {
        
        rd_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 rd = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearRd() {
        
        rd_ = 0;
        onChanged();
        return this;
      }

      private long data_ ;
      /**
       * <code>uint64 data = 2;</code>
       * @return The data.
       */
      @java.lang.Override
      public long getData() {
        return data_;
      }
      /**
       * <code>uint64 data = 2;</code>
       * @param value The data to set.
       * @return This builder for chaining.
       */
      public Builder setData(long value) {
        
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 data = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearData() {
        
        data_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:verif.RoCCResponse)
    }

    // @@protoc_insertion_point(class_scope:verif.RoCCResponse)
    private static final com.verif.RoCCProtos.RoCCResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.verif.RoCCProtos.RoCCResponse();
    }

    public static com.verif.RoCCProtos.RoCCResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RoCCResponse>
        PARSER = new com.google.protobuf.AbstractParser<RoCCResponse>() {
      @java.lang.Override
      public RoCCResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RoCCResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RoCCResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RoCCResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.verif.RoCCProtos.RoCCResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_verif_RoCCCommandAck_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_verif_RoCCCommandAck_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_verif_RoCCInstruction_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_verif_RoCCInstruction_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_verif_RoCCCommand_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_verif_RoCCCommand_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_verif_RoCCResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_verif_RoCCResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nRoCC.proto\022\005verif\"\035\n\016RoCCCommandAck\022\013\n" +
      "\003ack\030\001 \001(\r\"|\n\017RoCCInstruction\022\r\n\005funct\030\001" +
      " \001(\r\022\013\n\003rs2\030\002 \001(\r\022\013\n\003rs1\030\003 \001(\r\022\n\n\002xd\030\004 \001" +
      "(\010\022\013\n\003xs1\030\005 \001(\010\022\013\n\003xs2\030\006 \001(\010\022\n\n\002rd\030\007 \001(\r" +
      "\022\016\n\006opcode\030\010 \001(\r\"M\n\013RoCCCommand\022$\n\004inst\030" +
      "\001 \001(\0132\026.verif.RoCCInstruction\022\013\n\003rs1\030\002 \001" +
      "(\004\022\013\n\003rs2\030\003 \001(\004\"(\n\014RoCCResponse\022\n\n\002rd\030\001 " +
      "\001(\r\022\014\n\004data\030\002 \001(\0042T\n\022RoCCCommandChannel\022" +
      ">\n\017SendRoCCCommand\022\022.verif.RoCCCommand\032\025" +
      ".verif.RoCCCommandAck\"\000B\027\n\tcom.verifB\nRo" +
      "CCProtosb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_verif_RoCCCommandAck_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_verif_RoCCCommandAck_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_verif_RoCCCommandAck_descriptor,
        new java.lang.String[] { "Ack", });
    internal_static_verif_RoCCInstruction_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_verif_RoCCInstruction_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_verif_RoCCInstruction_descriptor,
        new java.lang.String[] { "Funct", "Rs2", "Rs1", "Xd", "Xs1", "Xs2", "Rd", "Opcode", });
    internal_static_verif_RoCCCommand_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_verif_RoCCCommand_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_verif_RoCCCommand_descriptor,
        new java.lang.String[] { "Inst", "Rs1", "Rs2", });
    internal_static_verif_RoCCResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_verif_RoCCResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_verif_RoCCResponse_descriptor,
        new java.lang.String[] { "Rd", "Data", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
