// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TL.proto

package com.verif;

public final class TLProtos {
  private TLProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TLAOrBuilder extends
      // @@protoc_insertion_point(interface_extends:verif.TLA)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint32 opcode = 1;</code>
     * @return The opcode.
     */
    int getOpcode();

    /**
     * <code>uint32 param = 2;</code>
     * @return The param.
     */
    int getParam();

    /**
     * <code>uint32 size = 3;</code>
     * @return The size.
     */
    int getSize();

    /**
     * <code>uint32 source = 4;</code>
     * @return The source.
     */
    int getSource();

    /**
     * <code>uint32 address = 5;</code>
     * @return The address.
     */
    int getAddress();

    /**
     * <pre>
     * user
     * echo
     * </pre>
     *
     * <code>uint32 mask = 6;</code>
     * @return The mask.
     */
    int getMask();

    /**
     * <code>bytes data = 7;</code>
     * @return The data.
     */
    com.google.protobuf.ByteString getData();

    /**
     * <code>bool corrupt = 8;</code>
     * @return The corrupt.
     */
    boolean getCorrupt();
  }
  /**
   * Protobuf type {@code verif.TLA}
   */
  public static final class TLA extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:verif.TLA)
      TLAOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TLA.newBuilder() to construct.
    private TLA(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TLA() {
      data_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new TLA();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TLA(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              opcode_ = input.readUInt32();
              break;
            }
            case 16: {

              param_ = input.readUInt32();
              break;
            }
            case 24: {

              size_ = input.readUInt32();
              break;
            }
            case 32: {

              source_ = input.readUInt32();
              break;
            }
            case 40: {

              address_ = input.readUInt32();
              break;
            }
            case 48: {

              mask_ = input.readUInt32();
              break;
            }
            case 58: {

              data_ = input.readBytes();
              break;
            }
            case 64: {

              corrupt_ = input.readBool();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.verif.TLProtos.internal_static_verif_TLA_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.verif.TLProtos.internal_static_verif_TLA_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.verif.TLProtos.TLA.class, com.verif.TLProtos.TLA.Builder.class);
    }

    public static final int OPCODE_FIELD_NUMBER = 1;
    private int opcode_;
    /**
     * <code>uint32 opcode = 1;</code>
     * @return The opcode.
     */
    @java.lang.Override
    public int getOpcode() {
      return opcode_;
    }

    public static final int PARAM_FIELD_NUMBER = 2;
    private int param_;
    /**
     * <code>uint32 param = 2;</code>
     * @return The param.
     */
    @java.lang.Override
    public int getParam() {
      return param_;
    }

    public static final int SIZE_FIELD_NUMBER = 3;
    private int size_;
    /**
     * <code>uint32 size = 3;</code>
     * @return The size.
     */
    @java.lang.Override
    public int getSize() {
      return size_;
    }

    public static final int SOURCE_FIELD_NUMBER = 4;
    private int source_;
    /**
     * <code>uint32 source = 4;</code>
     * @return The source.
     */
    @java.lang.Override
    public int getSource() {
      return source_;
    }

    public static final int ADDRESS_FIELD_NUMBER = 5;
    private int address_;
    /**
     * <code>uint32 address = 5;</code>
     * @return The address.
     */
    @java.lang.Override
    public int getAddress() {
      return address_;
    }

    public static final int MASK_FIELD_NUMBER = 6;
    private int mask_;
    /**
     * <pre>
     * user
     * echo
     * </pre>
     *
     * <code>uint32 mask = 6;</code>
     * @return The mask.
     */
    @java.lang.Override
    public int getMask() {
      return mask_;
    }

    public static final int DATA_FIELD_NUMBER = 7;
    private com.google.protobuf.ByteString data_;
    /**
     * <code>bytes data = 7;</code>
     * @return The data.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    public static final int CORRUPT_FIELD_NUMBER = 8;
    private boolean corrupt_;
    /**
     * <code>bool corrupt = 8;</code>
     * @return The corrupt.
     */
    @java.lang.Override
    public boolean getCorrupt() {
      return corrupt_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (opcode_ != 0) {
        output.writeUInt32(1, opcode_);
      }
      if (param_ != 0) {
        output.writeUInt32(2, param_);
      }
      if (size_ != 0) {
        output.writeUInt32(3, size_);
      }
      if (source_ != 0) {
        output.writeUInt32(4, source_);
      }
      if (address_ != 0) {
        output.writeUInt32(5, address_);
      }
      if (mask_ != 0) {
        output.writeUInt32(6, mask_);
      }
      if (!data_.isEmpty()) {
        output.writeBytes(7, data_);
      }
      if (corrupt_ != false) {
        output.writeBool(8, corrupt_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (opcode_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, opcode_);
      }
      if (param_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, param_);
      }
      if (size_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, size_);
      }
      if (source_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(4, source_);
      }
      if (address_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(5, address_);
      }
      if (mask_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(6, mask_);
      }
      if (!data_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, data_);
      }
      if (corrupt_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(8, corrupt_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.verif.TLProtos.TLA)) {
        return super.equals(obj);
      }
      com.verif.TLProtos.TLA other = (com.verif.TLProtos.TLA) obj;

      if (getOpcode()
          != other.getOpcode()) return false;
      if (getParam()
          != other.getParam()) return false;
      if (getSize()
          != other.getSize()) return false;
      if (getSource()
          != other.getSource()) return false;
      if (getAddress()
          != other.getAddress()) return false;
      if (getMask()
          != other.getMask()) return false;
      if (!getData()
          .equals(other.getData())) return false;
      if (getCorrupt()
          != other.getCorrupt()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + OPCODE_FIELD_NUMBER;
      hash = (53 * hash) + getOpcode();
      hash = (37 * hash) + PARAM_FIELD_NUMBER;
      hash = (53 * hash) + getParam();
      hash = (37 * hash) + SIZE_FIELD_NUMBER;
      hash = (53 * hash) + getSize();
      hash = (37 * hash) + SOURCE_FIELD_NUMBER;
      hash = (53 * hash) + getSource();
      hash = (37 * hash) + ADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + getAddress();
      hash = (37 * hash) + MASK_FIELD_NUMBER;
      hash = (53 * hash) + getMask();
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData().hashCode();
      hash = (37 * hash) + CORRUPT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getCorrupt());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.verif.TLProtos.TLA parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.verif.TLProtos.TLA parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.verif.TLProtos.TLA parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.verif.TLProtos.TLA parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.verif.TLProtos.TLA parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.verif.TLProtos.TLA parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.verif.TLProtos.TLA parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.verif.TLProtos.TLA parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.verif.TLProtos.TLA parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.verif.TLProtos.TLA parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.verif.TLProtos.TLA parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.verif.TLProtos.TLA parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.verif.TLProtos.TLA prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code verif.TLA}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:verif.TLA)
        com.verif.TLProtos.TLAOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.verif.TLProtos.internal_static_verif_TLA_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.verif.TLProtos.internal_static_verif_TLA_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.verif.TLProtos.TLA.class, com.verif.TLProtos.TLA.Builder.class);
      }

      // Construct using com.verif.TLProtos.TLA.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        opcode_ = 0;

        param_ = 0;

        size_ = 0;

        source_ = 0;

        address_ = 0;

        mask_ = 0;

        data_ = com.google.protobuf.ByteString.EMPTY;

        corrupt_ = false;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.verif.TLProtos.internal_static_verif_TLA_descriptor;
      }

      @java.lang.Override
      public com.verif.TLProtos.TLA getDefaultInstanceForType() {
        return com.verif.TLProtos.TLA.getDefaultInstance();
      }

      @java.lang.Override
      public com.verif.TLProtos.TLA build() {
        com.verif.TLProtos.TLA result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.verif.TLProtos.TLA buildPartial() {
        com.verif.TLProtos.TLA result = new com.verif.TLProtos.TLA(this);
        result.opcode_ = opcode_;
        result.param_ = param_;
        result.size_ = size_;
        result.source_ = source_;
        result.address_ = address_;
        result.mask_ = mask_;
        result.data_ = data_;
        result.corrupt_ = corrupt_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.verif.TLProtos.TLA) {
          return mergeFrom((com.verif.TLProtos.TLA)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.verif.TLProtos.TLA other) {
        if (other == com.verif.TLProtos.TLA.getDefaultInstance()) return this;
        if (other.getOpcode() != 0) {
          setOpcode(other.getOpcode());
        }
        if (other.getParam() != 0) {
          setParam(other.getParam());
        }
        if (other.getSize() != 0) {
          setSize(other.getSize());
        }
        if (other.getSource() != 0) {
          setSource(other.getSource());
        }
        if (other.getAddress() != 0) {
          setAddress(other.getAddress());
        }
        if (other.getMask() != 0) {
          setMask(other.getMask());
        }
        if (other.getData() != com.google.protobuf.ByteString.EMPTY) {
          setData(other.getData());
        }
        if (other.getCorrupt() != false) {
          setCorrupt(other.getCorrupt());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.verif.TLProtos.TLA parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.verif.TLProtos.TLA) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int opcode_ ;
      /**
       * <code>uint32 opcode = 1;</code>
       * @return The opcode.
       */
      @java.lang.Override
      public int getOpcode() {
        return opcode_;
      }
      /**
       * <code>uint32 opcode = 1;</code>
       * @param value The opcode to set.
       * @return This builder for chaining.
       */
      public Builder setOpcode(int value) {
        
        opcode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 opcode = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearOpcode() {
        
        opcode_ = 0;
        onChanged();
        return this;
      }

      private int param_ ;
      /**
       * <code>uint32 param = 2;</code>
       * @return The param.
       */
      @java.lang.Override
      public int getParam() {
        return param_;
      }
      /**
       * <code>uint32 param = 2;</code>
       * @param value The param to set.
       * @return This builder for chaining.
       */
      public Builder setParam(int value) {
        
        param_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 param = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearParam() {
        
        param_ = 0;
        onChanged();
        return this;
      }

      private int size_ ;
      /**
       * <code>uint32 size = 3;</code>
       * @return The size.
       */
      @java.lang.Override
      public int getSize() {
        return size_;
      }
      /**
       * <code>uint32 size = 3;</code>
       * @param value The size to set.
       * @return This builder for chaining.
       */
      public Builder setSize(int value) {
        
        size_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 size = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearSize() {
        
        size_ = 0;
        onChanged();
        return this;
      }

      private int source_ ;
      /**
       * <code>uint32 source = 4;</code>
       * @return The source.
       */
      @java.lang.Override
      public int getSource() {
        return source_;
      }
      /**
       * <code>uint32 source = 4;</code>
       * @param value The source to set.
       * @return This builder for chaining.
       */
      public Builder setSource(int value) {
        
        source_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 source = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearSource() {
        
        source_ = 0;
        onChanged();
        return this;
      }

      private int address_ ;
      /**
       * <code>uint32 address = 5;</code>
       * @return The address.
       */
      @java.lang.Override
      public int getAddress() {
        return address_;
      }
      /**
       * <code>uint32 address = 5;</code>
       * @param value The address to set.
       * @return This builder for chaining.
       */
      public Builder setAddress(int value) {
        
        address_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 address = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearAddress() {
        
        address_ = 0;
        onChanged();
        return this;
      }

      private int mask_ ;
      /**
       * <pre>
       * user
       * echo
       * </pre>
       *
       * <code>uint32 mask = 6;</code>
       * @return The mask.
       */
      @java.lang.Override
      public int getMask() {
        return mask_;
      }
      /**
       * <pre>
       * user
       * echo
       * </pre>
       *
       * <code>uint32 mask = 6;</code>
       * @param value The mask to set.
       * @return This builder for chaining.
       */
      public Builder setMask(int value) {
        
        mask_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * user
       * echo
       * </pre>
       *
       * <code>uint32 mask = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearMask() {
        
        mask_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes data = 7;</code>
       * @return The data.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      /**
       * <code>bytes data = 7;</code>
       * @param value The data to set.
       * @return This builder for chaining.
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes data = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearData() {
        
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }

      private boolean corrupt_ ;
      /**
       * <code>bool corrupt = 8;</code>
       * @return The corrupt.
       */
      @java.lang.Override
      public boolean getCorrupt() {
        return corrupt_;
      }
      /**
       * <code>bool corrupt = 8;</code>
       * @param value The corrupt to set.
       * @return This builder for chaining.
       */
      public Builder setCorrupt(boolean value) {
        
        corrupt_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool corrupt = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearCorrupt() {
        
        corrupt_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:verif.TLA)
    }

    // @@protoc_insertion_point(class_scope:verif.TLA)
    private static final com.verif.TLProtos.TLA DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.verif.TLProtos.TLA();
    }

    public static com.verif.TLProtos.TLA getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TLA>
        PARSER = new com.google.protobuf.AbstractParser<TLA>() {
      @java.lang.Override
      public TLA parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TLA(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TLA> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TLA> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.verif.TLProtos.TLA getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface TLDOrBuilder extends
      // @@protoc_insertion_point(interface_extends:verif.TLD)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint32 opcode = 1;</code>
     * @return The opcode.
     */
    int getOpcode();

    /**
     * <code>uint32 param = 2;</code>
     * @return The param.
     */
    int getParam();

    /**
     * <code>uint32 size = 3;</code>
     * @return The size.
     */
    int getSize();

    /**
     * <code>uint32 source = 4;</code>
     * @return The source.
     */
    int getSource();

    /**
     * <code>uint32 sink = 5;</code>
     * @return The sink.
     */
    int getSink();

    /**
     * <code>bool denied = 6;</code>
     * @return The denied.
     */
    boolean getDenied();

    /**
     * <pre>
     * user
     * echo
     * </pre>
     *
     * <code>bytes data = 7;</code>
     * @return The data.
     */
    com.google.protobuf.ByteString getData();

    /**
     * <code>bool corrupt = 8;</code>
     * @return The corrupt.
     */
    boolean getCorrupt();
  }
  /**
   * Protobuf type {@code verif.TLD}
   */
  public static final class TLD extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:verif.TLD)
      TLDOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TLD.newBuilder() to construct.
    private TLD(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TLD() {
      data_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new TLD();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TLD(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              opcode_ = input.readUInt32();
              break;
            }
            case 16: {

              param_ = input.readUInt32();
              break;
            }
            case 24: {

              size_ = input.readUInt32();
              break;
            }
            case 32: {

              source_ = input.readUInt32();
              break;
            }
            case 40: {

              sink_ = input.readUInt32();
              break;
            }
            case 48: {

              denied_ = input.readBool();
              break;
            }
            case 58: {

              data_ = input.readBytes();
              break;
            }
            case 64: {

              corrupt_ = input.readBool();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.verif.TLProtos.internal_static_verif_TLD_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.verif.TLProtos.internal_static_verif_TLD_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.verif.TLProtos.TLD.class, com.verif.TLProtos.TLD.Builder.class);
    }

    public static final int OPCODE_FIELD_NUMBER = 1;
    private int opcode_;
    /**
     * <code>uint32 opcode = 1;</code>
     * @return The opcode.
     */
    @java.lang.Override
    public int getOpcode() {
      return opcode_;
    }

    public static final int PARAM_FIELD_NUMBER = 2;
    private int param_;
    /**
     * <code>uint32 param = 2;</code>
     * @return The param.
     */
    @java.lang.Override
    public int getParam() {
      return param_;
    }

    public static final int SIZE_FIELD_NUMBER = 3;
    private int size_;
    /**
     * <code>uint32 size = 3;</code>
     * @return The size.
     */
    @java.lang.Override
    public int getSize() {
      return size_;
    }

    public static final int SOURCE_FIELD_NUMBER = 4;
    private int source_;
    /**
     * <code>uint32 source = 4;</code>
     * @return The source.
     */
    @java.lang.Override
    public int getSource() {
      return source_;
    }

    public static final int SINK_FIELD_NUMBER = 5;
    private int sink_;
    /**
     * <code>uint32 sink = 5;</code>
     * @return The sink.
     */
    @java.lang.Override
    public int getSink() {
      return sink_;
    }

    public static final int DENIED_FIELD_NUMBER = 6;
    private boolean denied_;
    /**
     * <code>bool denied = 6;</code>
     * @return The denied.
     */
    @java.lang.Override
    public boolean getDenied() {
      return denied_;
    }

    public static final int DATA_FIELD_NUMBER = 7;
    private com.google.protobuf.ByteString data_;
    /**
     * <pre>
     * user
     * echo
     * </pre>
     *
     * <code>bytes data = 7;</code>
     * @return The data.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    public static final int CORRUPT_FIELD_NUMBER = 8;
    private boolean corrupt_;
    /**
     * <code>bool corrupt = 8;</code>
     * @return The corrupt.
     */
    @java.lang.Override
    public boolean getCorrupt() {
      return corrupt_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (opcode_ != 0) {
        output.writeUInt32(1, opcode_);
      }
      if (param_ != 0) {
        output.writeUInt32(2, param_);
      }
      if (size_ != 0) {
        output.writeUInt32(3, size_);
      }
      if (source_ != 0) {
        output.writeUInt32(4, source_);
      }
      if (sink_ != 0) {
        output.writeUInt32(5, sink_);
      }
      if (denied_ != false) {
        output.writeBool(6, denied_);
      }
      if (!data_.isEmpty()) {
        output.writeBytes(7, data_);
      }
      if (corrupt_ != false) {
        output.writeBool(8, corrupt_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (opcode_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, opcode_);
      }
      if (param_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, param_);
      }
      if (size_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, size_);
      }
      if (source_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(4, source_);
      }
      if (sink_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(5, sink_);
      }
      if (denied_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(6, denied_);
      }
      if (!data_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, data_);
      }
      if (corrupt_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(8, corrupt_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.verif.TLProtos.TLD)) {
        return super.equals(obj);
      }
      com.verif.TLProtos.TLD other = (com.verif.TLProtos.TLD) obj;

      if (getOpcode()
          != other.getOpcode()) return false;
      if (getParam()
          != other.getParam()) return false;
      if (getSize()
          != other.getSize()) return false;
      if (getSource()
          != other.getSource()) return false;
      if (getSink()
          != other.getSink()) return false;
      if (getDenied()
          != other.getDenied()) return false;
      if (!getData()
          .equals(other.getData())) return false;
      if (getCorrupt()
          != other.getCorrupt()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + OPCODE_FIELD_NUMBER;
      hash = (53 * hash) + getOpcode();
      hash = (37 * hash) + PARAM_FIELD_NUMBER;
      hash = (53 * hash) + getParam();
      hash = (37 * hash) + SIZE_FIELD_NUMBER;
      hash = (53 * hash) + getSize();
      hash = (37 * hash) + SOURCE_FIELD_NUMBER;
      hash = (53 * hash) + getSource();
      hash = (37 * hash) + SINK_FIELD_NUMBER;
      hash = (53 * hash) + getSink();
      hash = (37 * hash) + DENIED_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getDenied());
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData().hashCode();
      hash = (37 * hash) + CORRUPT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getCorrupt());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.verif.TLProtos.TLD parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.verif.TLProtos.TLD parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.verif.TLProtos.TLD parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.verif.TLProtos.TLD parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.verif.TLProtos.TLD parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.verif.TLProtos.TLD parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.verif.TLProtos.TLD parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.verif.TLProtos.TLD parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.verif.TLProtos.TLD parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.verif.TLProtos.TLD parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.verif.TLProtos.TLD parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.verif.TLProtos.TLD parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.verif.TLProtos.TLD prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code verif.TLD}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:verif.TLD)
        com.verif.TLProtos.TLDOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.verif.TLProtos.internal_static_verif_TLD_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.verif.TLProtos.internal_static_verif_TLD_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.verif.TLProtos.TLD.class, com.verif.TLProtos.TLD.Builder.class);
      }

      // Construct using com.verif.TLProtos.TLD.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        opcode_ = 0;

        param_ = 0;

        size_ = 0;

        source_ = 0;

        sink_ = 0;

        denied_ = false;

        data_ = com.google.protobuf.ByteString.EMPTY;

        corrupt_ = false;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.verif.TLProtos.internal_static_verif_TLD_descriptor;
      }

      @java.lang.Override
      public com.verif.TLProtos.TLD getDefaultInstanceForType() {
        return com.verif.TLProtos.TLD.getDefaultInstance();
      }

      @java.lang.Override
      public com.verif.TLProtos.TLD build() {
        com.verif.TLProtos.TLD result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.verif.TLProtos.TLD buildPartial() {
        com.verif.TLProtos.TLD result = new com.verif.TLProtos.TLD(this);
        result.opcode_ = opcode_;
        result.param_ = param_;
        result.size_ = size_;
        result.source_ = source_;
        result.sink_ = sink_;
        result.denied_ = denied_;
        result.data_ = data_;
        result.corrupt_ = corrupt_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.verif.TLProtos.TLD) {
          return mergeFrom((com.verif.TLProtos.TLD)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.verif.TLProtos.TLD other) {
        if (other == com.verif.TLProtos.TLD.getDefaultInstance()) return this;
        if (other.getOpcode() != 0) {
          setOpcode(other.getOpcode());
        }
        if (other.getParam() != 0) {
          setParam(other.getParam());
        }
        if (other.getSize() != 0) {
          setSize(other.getSize());
        }
        if (other.getSource() != 0) {
          setSource(other.getSource());
        }
        if (other.getSink() != 0) {
          setSink(other.getSink());
        }
        if (other.getDenied() != false) {
          setDenied(other.getDenied());
        }
        if (other.getData() != com.google.protobuf.ByteString.EMPTY) {
          setData(other.getData());
        }
        if (other.getCorrupt() != false) {
          setCorrupt(other.getCorrupt());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.verif.TLProtos.TLD parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.verif.TLProtos.TLD) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int opcode_ ;
      /**
       * <code>uint32 opcode = 1;</code>
       * @return The opcode.
       */
      @java.lang.Override
      public int getOpcode() {
        return opcode_;
      }
      /**
       * <code>uint32 opcode = 1;</code>
       * @param value The opcode to set.
       * @return This builder for chaining.
       */
      public Builder setOpcode(int value) {
        
        opcode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 opcode = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearOpcode() {
        
        opcode_ = 0;
        onChanged();
        return this;
      }

      private int param_ ;
      /**
       * <code>uint32 param = 2;</code>
       * @return The param.
       */
      @java.lang.Override
      public int getParam() {
        return param_;
      }
      /**
       * <code>uint32 param = 2;</code>
       * @param value The param to set.
       * @return This builder for chaining.
       */
      public Builder setParam(int value) {
        
        param_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 param = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearParam() {
        
        param_ = 0;
        onChanged();
        return this;
      }

      private int size_ ;
      /**
       * <code>uint32 size = 3;</code>
       * @return The size.
       */
      @java.lang.Override
      public int getSize() {
        return size_;
      }
      /**
       * <code>uint32 size = 3;</code>
       * @param value The size to set.
       * @return This builder for chaining.
       */
      public Builder setSize(int value) {
        
        size_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 size = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearSize() {
        
        size_ = 0;
        onChanged();
        return this;
      }

      private int source_ ;
      /**
       * <code>uint32 source = 4;</code>
       * @return The source.
       */
      @java.lang.Override
      public int getSource() {
        return source_;
      }
      /**
       * <code>uint32 source = 4;</code>
       * @param value The source to set.
       * @return This builder for chaining.
       */
      public Builder setSource(int value) {
        
        source_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 source = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearSource() {
        
        source_ = 0;
        onChanged();
        return this;
      }

      private int sink_ ;
      /**
       * <code>uint32 sink = 5;</code>
       * @return The sink.
       */
      @java.lang.Override
      public int getSink() {
        return sink_;
      }
      /**
       * <code>uint32 sink = 5;</code>
       * @param value The sink to set.
       * @return This builder for chaining.
       */
      public Builder setSink(int value) {
        
        sink_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 sink = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearSink() {
        
        sink_ = 0;
        onChanged();
        return this;
      }

      private boolean denied_ ;
      /**
       * <code>bool denied = 6;</code>
       * @return The denied.
       */
      @java.lang.Override
      public boolean getDenied() {
        return denied_;
      }
      /**
       * <code>bool denied = 6;</code>
       * @param value The denied to set.
       * @return This builder for chaining.
       */
      public Builder setDenied(boolean value) {
        
        denied_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool denied = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearDenied() {
        
        denied_ = false;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * user
       * echo
       * </pre>
       *
       * <code>bytes data = 7;</code>
       * @return The data.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      /**
       * <pre>
       * user
       * echo
       * </pre>
       *
       * <code>bytes data = 7;</code>
       * @param value The data to set.
       * @return This builder for chaining.
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * user
       * echo
       * </pre>
       *
       * <code>bytes data = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearData() {
        
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }

      private boolean corrupt_ ;
      /**
       * <code>bool corrupt = 8;</code>
       * @return The corrupt.
       */
      @java.lang.Override
      public boolean getCorrupt() {
        return corrupt_;
      }
      /**
       * <code>bool corrupt = 8;</code>
       * @param value The corrupt to set.
       * @return This builder for chaining.
       */
      public Builder setCorrupt(boolean value) {
        
        corrupt_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool corrupt = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearCorrupt() {
        
        corrupt_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:verif.TLD)
    }

    // @@protoc_insertion_point(class_scope:verif.TLD)
    private static final com.verif.TLProtos.TLD DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.verif.TLProtos.TLD();
    }

    public static com.verif.TLProtos.TLD getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TLD>
        PARSER = new com.google.protobuf.AbstractParser<TLD>() {
      @java.lang.Override
      public TLD parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TLD(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TLD> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TLD> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.verif.TLProtos.TLD getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_verif_TLA_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_verif_TLA_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_verif_TLD_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_verif_TLD_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\010TL.proto\022\005verif\"\200\001\n\003TLA\022\016\n\006opcode\030\001 \001(" +
      "\r\022\r\n\005param\030\002 \001(\r\022\014\n\004size\030\003 \001(\r\022\016\n\006source" +
      "\030\004 \001(\r\022\017\n\007address\030\005 \001(\r\022\014\n\004mask\030\006 \001(\r\022\014\n" +
      "\004data\030\007 \001(\014\022\017\n\007corrupt\030\010 \001(\010\"\177\n\003TLD\022\016\n\006o" +
      "pcode\030\001 \001(\r\022\r\n\005param\030\002 \001(\r\022\014\n\004size\030\003 \001(\r" +
      "\022\016\n\006source\030\004 \001(\r\022\014\n\004sink\030\005 \001(\r\022\016\n\006denied" +
      "\030\006 \001(\010\022\014\n\004data\030\007 \001(\014\022\017\n\007corrupt\030\010 \001(\010B\025\n" +
      "\tcom.verifB\010TLProtosb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_verif_TLA_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_verif_TLA_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_verif_TLA_descriptor,
        new java.lang.String[] { "Opcode", "Param", "Size", "Source", "Address", "Mask", "Data", "Corrupt", });
    internal_static_verif_TLD_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_verif_TLD_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_verif_TLD_descriptor,
        new java.lang.String[] { "Opcode", "Param", "Size", "Source", "Sink", "Denied", "Data", "Corrupt", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
